USE receptai;

create table RECEPTAI(
	RECEPTO_ID INT PRIMARY KEY auto_increment,
    PAVADINIMAS NVARCHAR(50),
    APRASYMAS NVARCHAR(255)
);

-- alter table RECEPTAI
-- DROP PAVEIKSLELIO_NUORODA;

-- alter table RECEPTAI
-- ADD PAVEIKSLELIO_NUORODA TEXT AFTER APRASYMAS;

UPDATE RECEPTAI SET PAVEIKSLELIO_NUORODA = 'https://i.ibb.co/Xyw2Sp0/mieline-tesla.jpg'
WHERE RECEPTO_ID in (1,5,6);

select * from RECEPTAI;

delete from RECEPTAI where RECEPTO_ID in (24,25);

INSERT INTO RECEPTAI VALUES (7,"Šviežios pirktos dešrelės ar kaimiška dešra", "Pirktos parduotuvėje šviežios dešrelės ar mamo gaminta kaimiška dešra visada tiks išalkusiam", "https://i.ibb.co/W2DZPPj/Sviezia-desra.jpg");

UPDATE RECEPTAI SET PAVEIKSLELIO_NUORODA="https://i.ibb.co/09D1ZxN/Sviezia-desra.jpg" WHERE RECEPTO_ID=7;

delete from RECEPTAI WHERE ID IN (5,6);

CREATE TABLE MATAVIMO_VIENETAI(
	MATAVIMO_VIENETO_ID INT PRIMARY KEY auto_increment,
    MATAVIMO_VIENETAS NCHAR(20)
);

ALTER TABLE MATAVIMO_VIENETAI ADD COLUMN MATAVIMO_VIENETAS VARCHAR(20) AFTER MATAVIMO_VIENETO_ID;
ALTER TABLE MATAVIMO_VIENETAI DROP COLUMN MATAVIMO_VNT;

SELECT * FROM MATAVIMO_VIENETAI;
UPDATE MATAVIMO_VIENETAI SET MATAVIMO_VIENETAS = MATAVIMO_VNT;

INSERT INTO MATAVIMO_VIENETAI VALUES (1, "gr.");
INSERT INTO MATAVIMO_VIENETAI VALUES (2, "kg.");
INSERT INTO MATAVIMO_VIENETAI VALUES (3, "vnt.");
INSERT INTO MATAVIMO_VIENETAI VALUES (4, "l.");
INSERT INTO MATAVIMO_VIENETAI VALUES (5, "v. š.");
INSERT INTO MATAVIMO_VIENETAI VALUES (6, "a. š.");
INSERT INTO MATAVIMO_VIENETAI VALUES (7, "stikl.");

CREATE TABLE INGREDIENTAI(
	INGREDIENTO_ID INT PRIMARY KEY auto_increment,
    INGREDIENTAS NVARCHAR (50),
    KIEKIS DECIMAL(6,2),
    RECEPTO_ID INT,
    FOREIGN KEY (RECEPTO_ID)
		REFERENCES RECEPTAI(RECEPTO_ID)
        ON DELETE CASCADE,
	MATAVIMO_VIENETO_ID INT,
	FOREIGN KEY (MATAVIMO_VIENETO_ID)
		REFERENCES MATAVIMO_VIENETAI(MATAVIMO_VIENETO_ID)
        ON DELETE RESTRICT        
);

INSERT INTO INGREDIENTAI VALUES (1, "Sausos mielės",  NULL, 1, NULL);
INSERT INTO INGREDIENTAI VALUES (2, "Pienas",  NULL, 1, NULL);
INSERT INTO INGREDIENTAI VALUES (3, "Kiaušiniai",  1, 1, 3);

select * from INGREDIENTAI;

CREATE TABLE GAMYBOS_ZINGSNIAI(
	GAMYBOS_EIGOS_ID INT PRIMARY KEY auto_increment,
    ZINGSNIO_NUMERIS INT,
    ZINGSNIS NVARCHAR(255),
    RECEPTO_ID INT,
    FOREIGN KEY (RECEPTO_ID)
		REFERENCES RECEPTAI(RECEPTO_ID)
        ON DELETE CASCADE
);
INSERT INTO GAMYBOS_ZINGSNIAI VALUES (1, 1, "Pasiimi puoduką", 1);
INSERT INTO GAMYBOS_ZINGSNIAI VALUES (2, 2, "Sudėti mieles ir pasmulkinti", 1);
INSERT INTO GAMYBOS_ZINGSNIAI VALUES (3, 3, "Mieles apsemti pienu", 1);

SELECT * FROM GAMYBOS_ZINGSNIAI;